### ISSUE TITLE
Plugin Clean Architecture

### ISSUE THREAD

**Issue by japhernandez** [sistemasnegros/api-hex-arch-express-types#1]
https://www.npmjs.com/package/clean-scaffold?activeTab=dependencies                                                       
                                                                                    Te comparto este plugin que te crea una estructura de un proyecto para construir una API con NodeJs y TypeScript, basado en Arquitectura Limpia.

**Comment by sistemasnegros** [comment]
Hola, muy completo y muy configurable, muchas gracias!.
